IR: Use frozen dataclasses to enforce immutablity - Part 1
ecmwf-ifs/loki pull request #15
Opened 2023-01-10 08:04 UTC by mlange05

_Note: This is part 1 of a double-header, which is first concerned with changing the definition and constructor usage of regular IR nodes. Part 2 will specifically focus on the constructor usage of `Scope` objects and expand the change presented here to `ScopedNode`s._

The core rationale behind this change is the fact that we currently use a lot of monkey-patching and hidden magic functions in our IR node definition to enforce pseudo-immutability. However, with Python 3.7+, dataclasses have been introduced that can be used to natively express all these concepts (immutable attributes; dict-like comparison; hashes based select attributes, ...) including the ability to declare an object `frozen=True` and thus prevent direct regular-style updates to the object. We can, however, keep our explicit back for in-place updates (`Node._update`) in place by accessing `Node.__dict__` directly.

The most crucial and high impact user-level change that this PR brings is the strict requirement to use keyword-only notation for `Node` constructors. From Python 3.10 onwards, we will be able to enforce this strictly via `kw_only=True`, but until then the requirement is implicit and will need updating of all(!) downstream scripts. On the other hand we now gain strict validation at constructor level via `pydantic`, which means any wrongly constructed (or re-constructed) Node will immediately fail if the provided type is incorrect. The reason for the keyword-only need comes from our use of inheritance, which would otherwise force the utility attributes (source, label) from the common base class to the front of `*args` (see [here](https://peps.python.org/pep-0557/#inheritance)).

Some more comments on the detailed implementation:
* In-place updates via `Node._update()` are supported via direct insertion into `Node.__dict__`
* `label` and `source` are now pure attributes, not properties
* the dataflow analysis attributes are kept as private copies and inserted directly into `Node.__dict__` in the post_init; this allows us to check the attachment from the properties as before, but means they are excluded from hash and comparison operators 
* `Node._args` is gone now, but custom comparison and hashes remain for now; this will be removed in part 2 (see next point)
* `ScopedNode` objects are not yet frozen dataclasses, as the way we construct `Scope` objects conflicts with this approach; there are several follow-on restrictions due to this:
  * we store the `Node._argnames` as a class attribute, so that we don't need `Node._args` anymore; this will eventually be removed again in part 2
  * We need to maintain custom dunder methods and custom canonical caching until we can switch the `Scope` to be pseudo-immutable too (in part 2)

As a final note, the concrete type definitions might not be ideal, since in a few cases I have to use `body: Tuple[Any, ...]` instead of `body: Tuple[Node, ...]`. This is due to the fact that our transformers are prone to inserting nested tuples ni some places, which would otherwise put more onus on the user scripts to `flatten` things super-rigorously. A further tidy up of the transformers could also be in order once part 2 has landed, but that is a "future work" item.

2023-02-27 16:31 UTC, mlange05 commented
@reuterbal Ok, I've changed the approach in this and updated the PR description accordingly. I _think_ I've also chased down the last few idiosyncrasies, but CI will confirm soon. I think it's ready for review now. 

One last comment is that, once the constructor checks were activated, I found a bunch of subtle undetectected bugs that I'e tried to fix in the head commit. It's noteworthy that these are not complete, and I think there is significant scope for improvement and for tightening some of these checks, but I leave that for a follow-up PR, as even re-creating current behaviour is not easy.

2023-03-03 21:10 UTC, reuterbal reviewed
Finally had a first look through this and really impressed! Not only is this a major improvement to the IR classes, but the fact that this significant change incurs so little modifications outside of `ir.py` really is an achievement!

I'm leaving just a few comments for now as I'd like to have a play with this a little to understand better some of the implications.

One specific question about the various type checks that are now in `__post_init__()`: How many of those are actually required or are possibly redundant thanks to pydantic? I might have a play with this myself to understand the behaviour a little better, could potentially yield a set of tests that check that wrong use of IR classes fails as expected.

2023-03-22 14:44 UTC, reuterbal requested changes
OK, nothing further in addition to my comments above. Please have a look and see which of those make sense.

2023-03-22 14:46 UTC, reuterbal commented on loki/frontend/ofp.py
> +            assert ncond == 1 and else_body is ()
One more comment: pytest doesn't like this particularly much:
```
loki/frontend/ofp.py:254
  /home/nabr/loki/naml-ir-dataclasses/loki/frontend/ofp.py:254: SyntaxWarning: "is" with a literal. Did you mean "=="?
    assert ncond == 1 and else_body is ()
```

2023-03-28 07:47 UTC, reuterbal commented on loki/frontend/fparser.py
> +            flatten(as_tuple(self.visit(c, **kwargs) for c in o.children[start+1:stop]))
Absolutely, it was a general remark anyway not an action item for now!

2023-03-28 07:55 UTC, mlange05 commented
@reuterbal Ok, finally managed to fix the underpinning issue that was tripping up full-physics transformations (see the commit related to preventing `Section.body` to become nested). I've also pushed fixes for the other comments, so I think this one is ready for another look. :smile: :pray:

2023-03-28 16:42 UTC, reuterbal commented
Thanks so much for chasing up all of that, looks great now and ready to be merged (curious about the fallout this is going to create ;-) )

2023-03-28 16:42 UTC, reuterbal approved these changes

2023-03-29 10:09 UTC, merged