Static Transformation properties (manifest)
ecmwf-ifs/loki pull request #154
Opened 2023-09-18 07:33 UTC by mlange05

This PR changes the way we configure the `Scheduler` behaviour for individual `Transformation` passes. Up until now, we rely on the user of a transformation to hand any special iteration properties (reverse graph traversal, program unit recursion, etc.) as run time argument to the scheduler, with no safeguards if the wrong behaviour is requested. 

This PR now changes this, so that `Transformation` objects carry a set of specific flags as class properties (the manifest) that can be overridden in the class definition. So far, this change only moves scheduler traversal behaviour and behaviour specific to `apply(...)` to the manifest, but it can easily be extended to capture other static meta-information, etc. 

In more detail:
* Moved `reverse_traversal`, `traverse_file_graph` and `item_filter` properties to the static class manifest. @reuterbal Please note that these are the main "graph traversal" configuration options that should eventually be implemented via the planned `SGraph` mechanisms. 
* Move the "program unit recursion" properties to the manifest, with fine-grained configuration behaviour over which recursion is required. Please note that this includes a few mechanisms specific to the `DependencyTransformation`, which we can hopefully simplify once that transformation is streamlined and/or we have the SGraph (@reuterbal )
* Fixes to various tests, and use of new configuration mechanism in `DependencyTransformation` and `GlobalVarTransformation`

2023-11-17 13:31 UTC, mlange05 commented
Ok, after quite some fixing and tweaking (some workarounds needed to be shifted, rather than resolved), the test base is now green. I've also rebased over latest main. So, I think this is worth another look @reuterbal ?

2023-11-29 12:08 UTC, reuterbal requested changes
Sorry for the latency, this is really great and a huge step forward towards a more formal procedure for planning and applying transformation passes. Overall no objections to any of the changes. 

I left a few remarks where I think the naming could be improved, but none of that is a hard requirement. I also noticed that we don't currently cover some of the recursion control flows in the test base but this was presumably the case already before, so not necessarily required to act on this now.

My main concern would be whether we really need the "wrong" metadata provided in the transformation invocation during file graph traversals. See inline comment for details.

2023-12-04 08:24 UTC, reuterbal commented on loki/transform/transformation.py
> +    traverse_file_graph = False
Agreed, leave as is and we can pick this up when it actually becomes relevant.

2023-12-04 08:35 UTC, reuterbal approved these changes
Many thanks, happy with the current state!

2023-12-05 12:57 UTC, merged