introduce 'flatten_arrays()' (to overcome pointer hack)
ecmwf-ifs/loki pull request #199
Opened 2023-12-15 09:54 UTC by MichaelSt98

**Usable and tested as drop in replacement for the CLOUDSC Loki C transpilation**

* do we want to keep the original *pointer hack* as another option or just replace it?

Convert e.g., 

```fortran
  INTEGER, INTENT(INOUT) :: x1(l1)
  INTEGER, INTENT(INOUT) :: x2(l2, l1)
  INTEGER, INTENT(INOUT) :: x3(l3, l2, l1)
  INTEGER, INTENT(INOUT) :: x4(l4, l3, l2, l1)
  DO i1=1,l1
    x1(i1) = ...
    DO i2=1,l2
      x2(i2, i1) = ...
      DO i3=1,l3
        x3(i3, i2, i1) = ...
        DO i4=1,l4
          x4(i4, i3, i2, i1) = ...
        END DO
      END DO
    END DO
  END DO
```

to:

```fortran
  INTEGER, INTENT(INOUT) :: x1(l1)
  INTEGER, INTENT(INOUT) :: x2(l2*l1)
  INTEGER, INTENT(INOUT) :: x3(l3*l2*l1)
  INTEGER, INTENT(INOUT) :: x4(l4*l3*l2*l1)
  DO i1=1,l1
    x1(i1) = ...
    DO i2=1,l2
      x2(i2 + l2*(i1 + -1)) = ...
      DO i3=1,l3
        x3(i3 + l3*(i2 + l2*(i1 + -1) + -1)) = ...
        DO i4=1,l4
          x4(i4 + l4*(i3 + l3*(i2 + l2*(i1 + -1) + -1) + -1)) = ...
        END DO
      END DO
    END DO
  END DO
```

**However:**

currently not handled are arrays like 

```fortran
NTEGER, INTENT(INOUT) :: x4(0:l4, 0:l3, 0:l2, 0:l1)
```

This complicates things a lot and the question is how to handle this especially regarding the f2c transpilation... thus, whether this utility should handle that or whether another utility/transformation before flattening the arrays is more appropriate.

2023-12-15 20:51 UTC, reuterbal requested changes
Thanks so much, this is a great addition and clean solution to the original pointer hack. I think there's no need to retain the original pointer variant.

I have left a few remarks throughout, minor things mostly. The testing could benefit from a sanity check on the IR level directly, and I've proposed a potential solution for range-based shapes.

2023-12-15 20:51 UTC, reuterbal commented on loki/transform/transform_array_indexing.py
> +        }
To improve our error reporting, I'd suggest not to use `assert` here but instead throw an exception in an else branch:
```suggestion
    if order == 'C':
        array_map = {
            var: var.clone(dimensions=new_dims(list(var.dimensions)[::-1], list(var.shape)[::-1]))
            for var in FindVariables().visit(routine.body)
                if isinstance(var, sym.Array) and var.shape and len(var.shape)
        }
    elif order == 'F':
        array_map = {
            var: var.clone(dimensions=new_dims(list(var.dimensions), list(var.shape)))
            for var in FindVariables().visit(routine.body)
                if isinstance(var, sym.Array) and var.shape and len(var.shape)
        }
    else:
        raise ValueError(f'Unsupported array order "{order}")
```

2023-12-15 20:51 UTC, reuterbal commented on loki/transform/transform_array_indexing.py
> +                if isinstance(var, sym.Array) and var.shape and len(var.shape)
It's ratehr unconventional to increase indentation here since you are not entering a new block/scope

2023-12-15 20:51 UTC, reuterbal commented on loki/transform/transform_array_indexing.py
> +            var: var.clone(dimensions=new_dims(list(var.dimensions), list(var.shape)))
I'd avoid the conversion to `list` here and the other uses. Instead, use a tuple for _dim and replace the call to `extend` in `new_dims` by `new_dim += _dim` which allows you to work directly with the tuples.

2023-12-15 20:51 UTC, reuterbal commented on loki/transform/transform_array_indexing.py
> +            _dim = [sym.Sum((dim[-2], sym.Product((shape[-2], dim[-1] - start_index))))]
A little confused by this: You are checking that `shape[-1]` isn't a `RangeIndex`, yet `shape[-2]` is the dimension you are actually using here. 
I might be thinking too simple here, but to accomodate the mentioned situation of
```f90
INTEGER, INTENT(INOUT) :: x4(0:l4, 0:l3, 0:l2, 0:l1)
```
would only require to add something like
```suggestion
            if isinstance(shape[-2], sym.RangeIndex):
                _len = sym.Sum((shape[-2].upper, sym.Product((-1, shape[-2].lower))))
                _start_index = sym.Sum((start_index, shape[-2].lower))
            else:
                _len = shape[-2]
                _start_index = start_index
            if isinstance(shape[-1], sym.RangeIndex):
                _start_index = sym.Sum((start_index, shape[-1].lower))
            else:
                _start_index = start_index
            _dim = [sym.Sum((
                dim[-2],
                sym.Product((
                    _len,
                    sym.Sum((
                        dim[-1],
                        sym.Product((-1, _start_index))
                    ))
                ))
            ))]
```

I'm almost sure I'm making some mistake here between what shape to use for which, but this should take care of the possibly longer or shorter dimension due to the non-standard shape, and the offset relative to this.

2023-12-15 20:51 UTC, reuterbal commented on tests/test_transform_array_indexing.py
> +    flatten_arrays(routine=f_routine, order='F', start_index=1)
I would propose to add some simple testing of the IR here as well. For example, look for all `Array` nodes in the body and make sure they all have `len(arr.dimension) == 1`.

2023-12-19 15:29 UTC, reuterbal reviewed
Very nice, thanks for this! I've left a few housekeeping remarks but otherwise this looks very promising.

Note that you may have to rebase over main again to avoid the regression tests from failing.

2023-12-19 16:35 UTC, MichaelSt98 commented on loki/transform/fortran_c_transform.py
>          normalize_range_indexing(kernel)
correct

2023-12-19 16:35 UTC, MichaelSt98 commented on loki/transform/transform_array_indexing.py
> +def normalize_array_access(routine):
Yes I agree, I'll go with `normalize_array_shape_and_access`

2023-12-19 19:16 UTC, reuterbal approved these changes
Great, everything looks fantastic now. 

@mlange05 do you want to confirm this is fine in offline regression tests?

2023-12-20 09:13 UTC, mlange05 approved these changes
Only had a brief look at code changes, but played with CLODUSC regression test. All seems good, so GTG from me. :shipit:

2023-12-20 09:59 UTC, MichaelSt98 commented
* Old/"pointer cast hack" version
    * compiles and runs with Intel
    * won't compile with NVHPC
* New/"index arithmetic" version
    * compiles and runs with Intel
    * compiles with NVHPC and runs for `NPROMA=1,2` 
        * however, floating point exception for different `NPROMA`
        * works with arbitrary `NPROMA` compiling with `-O0` instead of `-O2` (haven't checked for `-O1`)

2023-12-20 11:03 UTC, reuterbal commented
>         * however, floating point exception for different `NPROMA`
>         * works with arbitrary `NPROMA` compiling with `-O0` instead of `-O2` (haven't checked for `-O1`)

This suggests to me that we see one of the recurring vectorization-related issues. Does this occur in the kernel itself or the validation routine?

2023-12-20 11:25 UTC, MichaelSt98 commented
> > ```
> >     * however, floating point exception for different `NPROMA`
> >     * works with arbitrary `NPROMA` compiling with `-O0` instead of `-O2` (haven't checked for `-O1`)
> > ```
> 
> 
> This suggests to me that we see one of the recurring vectorization-related issues. Does this occur in the kernel itself or the validation routine?

Yes ... must be kernel itself, as the rest (including validation) is still (the original) Fortran?!

2023-12-20 13:22 UTC, merged