assumed size array handling for 'normalize_array_shape_and_access'
ecmwf-ifs/loki pull request #218
Opened 2024-01-25 10:42 UTC by MichaelSt98

`normalize_array_shape_and_access()` didn't handle assumed size arrays correctly. 
This is a proposed fix/extension.

2024-01-25 12:04 UTC, reuterbal requested changes
Thanks, looks good. Two suggestions where I think stuff could be simplified, otherwise GTG!

2024-01-25 12:04 UTC, reuterbal commented on loki/transform/transform_array_indexing.py
> +            if len(v.shape) != len(v.dimensions):
Shouldn't the only case be that `v.dimensions is None`? Otherwise, `shape` and `dimensions` should match or there's something fishy anyway.

2024-01-25 12:04 UTC, reuterbal commented on tests/test_transform_array_indexing.py
> +            # print(f"arr: {arr} | {all(not isinstance(shape, sym.RangeIndex) for shape in arr.shape)}")
```suggestion
```

2024-01-26 19:25 UTC, reuterbal approved these changes
Thanks for making these changes, looks good now!

2024-01-31 15:39 UTC, mlange05 approved these changes
Looks great, going in now. :shipit:

2024-01-31 15:40 UTC, merged