kwargs utilities
ecmwf-ifs/loki pull request #235
Opened 2024-03-04 10:22 UTC by MichaelSt98

Utilities for `CallStatement`s

* check whether `kwargs` are correctly ordered
* sort `kwargs`
* convert `kwargs` to args

necessary for e.g., F2C transpilation

2024-03-05 11:03 UTC, reuterbal requested changes
Thanks, this looks very useful! A little suggestion to improve naming, otherwise happy.

2024-03-05 11:03 UTC, reuterbal commented on loki/ir.py
> +    def kwargs_to_args(self):
Maybe use the "leading verb" naming here, too?

```suggestion
    def convert_kwargs_to_args(self):
```

2024-03-05 14:24 UTC, reuterbal approved these changes

2024-03-25 13:27 UTC, mlange05 approved these changes
Looks great! Many thanks for you patience. GTG from me. :shipit:

2024-03-25 14:00 UTC, merged