Hoist variables as `kwargs` (optionally)
ecmwf-ifs/loki pull request #237
Opened 2024-03-05 08:33 UTC by MichaelSt98

Hoist variables as `kwargs` (optionally)

2024-03-05 10:23 UTC, reuterbal requested changes
Thanks, that looks very useful! 
Just a little remark about parameterising tests, and a question on whether we may run into problems of `None + tuple()` with `call.kwarguments`.

2024-03-05 10:38 UTC, MichaelSt98 commented on tests/test_transform_hoist_variables.py
> +@pytest.mark.parametrize('as_kwarguments', ['False', 'True'])
There is no reason ... 😄 Thanks

2024-03-05 10:41 UTC, MichaelSt98 commented on loki/transform/transform_hoist_variables.py
> +            return call.clone(kwarguments=call.kwarguments + new_kwargs)
Good point, seems like it's possible that `call.kwarguments` could be `None`

2024-03-05 13:33 UTC, reuterbal approved these changes

2024-03-25 13:46 UTC, mlange05 approved these changes
Looks good. Many thanks for your patience. GTG :shipit:

2024-03-25 20:55 UTC, merged