Updates for EC-physics regression
ecmwf-ifs/loki pull request #252
Opened 2024-03-18 19:31 UTC by mlange05

This PR brings in a set of small changes (mostly discussed offline) that aligns the new scheduler with prior behaviour and thus gets EC-physics to pass again (in a reasonable amount of time). The main updates are concerned with the CMake-planning stage, where we need to re-introduce the `enable_imports` option and honour it for default parse traversals, as well as the disabling of the SGraph caching (which otherwise makes things prohibitively slow).

In some more detail:
* Reduce the logging of `make_complete` to only trigger on non-REGEX frontends
* Avoid self-reference cycles when building the SGraph (no longer needed after `ExternalItem` addition, but thought I'd keep it anyways)
* (Temporarily) stop caching the SGraph, and instead re-build it after each use of discovery and item-parsing. Note that this is meant as temporary until we can improve the re-build speed of large graphs via caching.
* Bugfix: Fix the bailout mechanism for parser_classes in `make_complete` with REGEX frontend (as suggested by @reuterbal )
* Re-introduce the `enable_imports` options for the `Scheduler`, which allows us to prune the search tree for EC-physics significantly

2024-03-19 10:39 UTC, reuterbal requested changes
Thanks, looks good in principle and happy to see this is beginning to converge to a useable solution.

This exposes `_discover()` and `_parse_items()` as the two conceptual steps that mandate a rebuild of the "master" graph, which sounds sensible (and the latter only because we fail/Fortran makes it impossible to detect some dependencies via regex'ing alone). 
To restore the clean algorithmic view of this and make the caching become an implementation detail, I think it might make sense to defer triggering the sgraph (re-)build directly to these two methods.

The change in default behaviour w.r.t. `enable_imports` causes a lot of tests to fail - I guess you will need to amend these tests in test_batch.py & co with the `enable_imports=True` constructor argument. We may also want to have at least one test for the `enable_imports=False` case - maybe some of these tests can be parameterised accordingly?

Same is true for the ecwam regression tests, where we need to enable imports again in the config. Do you want me to apply the change on the paired staging branch there?

Finally, it would be good to briefly document this option in the relevant section in the docs, probably somewhere in here:

https://github.com/ecmwf-ifs/loki/blob/31717002dd07368b24127d622f8bf9e9198dd082/docs/source/transform.rst?plain=1#L151-L216

2024-03-19 10:39 UTC, reuterbal commented on loki/bulk/scheduler.py
> +            self._sgraph = SGraph.from_seed(self.seeds, self.item_factory, self.config)
Given that `_discover()` and `_parse_items()` are now the two patterns which mandate a rebuild, I'm wondering if the `SGraph` construction and caching should not just be put in there?

2024-03-19 10:39 UTC, reuterbal commented on loki/bulk/scheduler.py
> +        for item in SFilter(self.sgraph, item_filter=item_filter):
Thinking loud here, but could we not do this directly via the filegraph? After all, we're after files here... That would automatically apply the filtering.

2024-03-19 11:01 UTC, reuterbal commented on loki/bulk/scheduler.py
> +        for item in SFilter(self.sgraph, item_filter=item_filter):
Ah, yes, in that case leave as is and maybe flag this in an issue? Probably more generally the concept of propagating item properties to file items. Just out of curiosity, how is that property specified in the first place?

2024-03-20 08:47 UTC, mlange05 commented
@reuterbal As discussed offline, I needed to revert the performance "fix" for parser_class comparison; I've left the revert commit in to get the test base green for now, but feel free to rebase out the respective pair of commits before merging into the main scheduler PR.

2024-03-20 18:31 UTC, reuterbal commented on loki/bulk/scheduler.py
> +        for item in SFilter(self.sgraph, item_filter=item_filter):
Filed #255 to track this

2024-03-20 18:32 UTC, reuterbal approved these changes
Thanks, looks good to me now. I'll put this in and mop up the documentation in the Scheduler branch directly.

2024-03-20 18:32 UTC, merged