`DataflowAnalysis` bugfix: preserve body nesting
ecmwf-ifs/loki pull request #288
Opened 2024-04-15 09:20 UTC by awnawab

The `_visit_body` method in the `DataflowAnalysis` flattens the bodies, which can sometimes lead to invalid IR. This PR provides a fix.

2024-04-15 11:09 UTC, reuterbal requested changes
Thanks, nice find!

While the fix produces the correct result, it is only working around the original bug. In `visit_MaskedStatement`, we are calling the routine with multiple bodies instead of separately per body, as in the other visitor methods:
https://github.com/ecmwf-ifs/loki/blob/88d865682b6a65342544fcb840257054bf3c69fe/loki/analyse/analyse_dataflow.py#L196

Would you mind trying if 
- a simple loop over the `bodies` property in `visit_MaskedStatement`
- and only removing the `flatten` in `_visit_body`
would yield the same result?

2024-04-15 12:48 UTC, awnawab commented
Thanks for the feedback 😄  I was trying to make `_visit_body` respect the nesting of tuples regardless of what any `visit_Node` method might do, but you are right, it is better to fix `visit_MaskedStatement` rather than let `_visit_body` mop-up any potential mistakes.

2024-04-15 15:38 UTC, reuterbal commented on tests/test_analyse_dataflow.py
>      vec1(:) = -5.0
If we removed this line, would `vec1` then also appear in the uses set?

2024-04-16 07:58 UTC, reuterbal approved these changes
Thanks, looks good to me now!

It needs another rebase, unfortunately, to resolve conflicts before we can merge.

2024-04-16 11:37 UTC, merged