Improve `parse_expr` and use in `process_dimension_pragmas`
ecmwf-ifs/loki pull request #292
Opened 2024-04-18 09:59 UTC by MichaelSt98

Improve `parse_expr` and use in `process_dimension_pragmas`.

* add correct parsing of `:` to `RangeIndex((None, None))`
* support `DerivedType` s

2024-04-19 11:46 UTC, MichaelSt98 commented
Some improvements to the expression parser included in this PR:

Executing:

```py
from loki import parse_expr

class Foo:
    val3 = 1
    arr = [[1, 2], [3, 4]]
    def __init__(self, _val1, _val2):
        self.val1 = _val1
        self.val2 = _val2
    def some_func(self, a, b):
        return a + b
    @staticmethod
    def static_func(a):
        return 2*a

context = {'foo': Foo(2, 3)}
test_str = 'foo%val1 + foo%val2 + foo%val3'
parsed = parse_expr(f'{test_str}')
print(f"parsing: {test_str} with context: '{context}'\n  results in '{parsed}'")
parsed = parse_expr(f'{test_str}', evaluate=True, context=context)
print(f"parsing and evaluating: {test_str} with context: '{context}'\n  results in '{parsed}'")
test_str = 'foo%val1 + foo%some_func(1, 2) + foo%static_func_2(3)'
parsed = parse_expr(f'{test_str}', evaluate=True, context=context)
print(f"parsing and evaluating: {test_str} with context: '{context}'\n  results in '{parsed}'")
test_str = 'foo%val1 + foo%some_func(1, 2) + foo%static_func(3) + foo%arr(1, 2)'
parsed = parse_expr(f'{test_str}', evaluate=True, context=context, strict=True)
print(f"parsing and evaluating: {test_str} with context: '{context}'\n  results in '{parsed}'")
test_str = 'foo%val1 + foo%some_func(1, b=2) + foo%static_func(a=3) + foo%arr(1, 2)'
parsed = parse_expr(f'{test_str}', evaluate=True, context=context, strict=True)
print(f"parsing and evaluating: {test_str} with context: '{context}'\n  results in '{parsed}'")
```

gives

```
parsing: foo%val1 + foo%val2 + foo%val3 with context: '{'foo': <__main__.Foo object at 0x1494ff19c3d0>}'
  results in 'foo%val1 + foo%val2 + foo%val3'
parsing and evaluating: foo%val1 + foo%val2 + foo%val3 with context: '{'foo': <__main__.Foo object at 0x1494ff19c3d0>}'
  results in '6'
parsing and evaluating: foo%val1 + foo%some_func(1, 2) + foo%static_func_2(3) with context: '{'foo': <__main__.Foo object at 0x1494ff19c3d0>}'
  results in '5 + foo%static_func_2(3)'
parsing and evaluating: foo%val1 + foo%some_func(1, 2) + foo%static_func(3) + foo%arr(1, 2) with context: '{'foo': <__main__.Foo object at 0x1494ff19c3d0>}'
  results in '13'
parsing and evaluating: foo%val1 + foo%some_func(1, b=2) + foo%static_func(a=3) + foo%arr(1, 2) with context: '{'foo': <__main__.Foo object at 0x1494ff19c3d0>}'
  results in '13'
```

2024-04-22 11:42 UTC, reuterbal requested changes
Many thanks, the improvements to `parse_expr` and how it can deal with derived types is absolutely fantastic! I'm really impressed by the degree of functionality you have created in a short amount of time.

Just out of curiosity but not necessarily something we need: would the evaluation also work for nested derived types? Say something like

```python
class Bar:
    baz = 4

class Foo:
    bar = Bar()

parse_expr('1 + foo%bar%baz', context={'foo': Foo()}, evaluate=True)
```

I am, however, not convinced by the integration in `process_dimension_pragmas`. The workaround with the expanded regex pattern breaks down as soon as there's more than one set of nested parentheses, and it's fundamentally a problem that cannot be solved by regex matching.

Therefore, I would propose to re-implement the `get_pragma_parameters` utility to provide this functionality. But we can also do this as a separate PR and leave out the support for parentheses in this PR.

2024-04-24 09:15 UTC, MichaelSt98 commented on loki/expression/tests/test_expression.py
> +
As discussed offline ...

2024-04-24 09:16 UTC, MichaelSt98 commented on loki/ir/pragma_utils.py
> +_get_pragma_dim_parameter_re = re.compile(r'(?P<command>[\w-]+)\s*(?:\((?P<arg>.*)\))?')
I agree. I did what you suggested based on the link you provided.

2024-04-24 09:20 UTC, MichaelSt98 commented
Regarding your nested derived types question:
It was not possible, but I've added a commit to allow nested derived types. 

With this, executing:

```py
from loki import parse_expr

class Bar:
    baz = 4

class Foo:
    bar = Bar()

ir = parse_expr('1 + foo%bar%baz', context={'foo': Foo()}, evaluate=True)
print(ir)
```

yields `5`.

There are also more sophisticated tests for nested derived types in `expression/tests/test_expression.py`

2024-04-24 09:25 UTC, MichaelSt98 commented on loki/expression/parser.py
> +        except Exception as e:
Hmm not sure how to narrow this down ... I want to catch any and all exceptions, possibly but not necessarily thrown by pymbolic (as some parent methods are called) ... Isn't `except Exception` exactly what to do in this case?

2024-04-24 09:44 UTC, reuterbal commented on loki/expression/parser.py
> +        except Exception as e:
Well, the purpose should be to gracefully handle only situations that you consider "safe" in this particular context - so, in this context likely situations like incomplete evaluation due to undefined variables/functions? Can these not be attributed to more specific exception classes. Unexpected exceptions should fall through verbatim and be dealt with at an outer level in my opinion.

2024-04-24 09:54 UTC, MichaelSt98 commented on loki/expression/parser.py
> +        except Exception as e:
I see your point. However, I (re)throw the exception if `self.strict = True` and the whole logic is to `try` what I want you to do e.g., evaluate the expression and if you fail for whatever reason just return the `ir`/`expression` (unless I want to have the evaluated expression and if this is not possible, throw the `exception` and tell me why this is not possible)?!

2024-04-25 10:33 UTC, reuterbal commented on loki/expression/parser.py
> +            raise NotImplementedError
Sorry, you're right of course. I missed the fact that we won't reach this point if it's one of the known "lookup" nodes. Thanks for clarifying!

2024-04-25 14:10 UTC, reuterbal approved these changes
Excellent, many thanks!

2024-04-25 14:50 UTC, merged