Docs: Update to links from static doc pages
ecmwf-ifs/loki pull request #312
Opened 2024-05-04 04:26 UTC by mlange05

_Filing early to get the resulting change and errors logs. Please ignore for now..._

2024-05-10 12:44 UTC, reuterbal requested changes
Love this, many thanks! I've flagged a few typos, otherwise good to go!

2024-05-10 12:44 UTC, reuterbal commented on loki/build/__init__.py
> +using `f90wrap <https://github.com/jameskermode/f90wrap>` for
```suggestion
using `f90wrap <https://github.com/jameskermode/f90wrap>`_ for
```

2024-05-10 12:44 UTC, reuterbal commented on loki/expression/__init__.py
> +<https://github.com/inducer/pymbolic`.
```suggestion
Expression layer of the two-level Loki IR based on
`Pymbolic <https://github.com/inducer/pymbolic>`_.
```

2024-05-10 12:44 UTC, reuterbal commented on loki/frontend/__init__.py
> +interfaces, including the REGEX-frontend that used for fast source
```suggestion
interfaces, including the REGEX-frontend that is used for fast source
```

2024-05-10 12:44 UTC, reuterbal commented on loki/frontend/__init__.py
> +code exploration in large call trees.
```suggestion
code exploration in large call and dependency trees.
```

2024-05-10 12:44 UTC, reuterbal commented on loki/transformations/__init__.py
> +This sub-package includes general source code trnasformations and
```suggestion
This sub-package includes general source code transformations and
```

2024-05-10 12:44 UTC, reuterbal commented on loki/batch/__init__.py
> +provides the basic :any:`Transformation` and :and:`Pipeline` classes
```suggestion
provides the basic :any:`Transformation` and :any:`Pipeline` classes
```

2024-05-10 14:09 UTC, mlange05 commented
Ok, thanks @reuterbal . Pushed fixes and rebased.

2024-05-12 20:11 UTC, reuterbal approved these changes
Thanks! There was a 1-letter typo still, which I took the liberty of fixing myself. Going in...

2024-05-12 20:11 UTC, merged