Transformations: Add `scc.util` for common utility routines
ecmwf-ifs/loki pull request #354
Opened 2024-07-29 11:47 UTC by mlange05

Another small housekeeping change. This one adds a new sub-package `transformations.single_column.util` sub-package for common utilities that may be used across the several SCC sub-stages. This primarily removes the awkward dependency on the `SCCBaseTransformation` class in other SCC sub-components, which provided this previously. 

This change is largely cosmetic (simply copying methods over), except for the `get_local_arrays` utility, which is now used by the demotion and the annotations sub-component. This is in preparation for a more complex refactoring of the annotation sub-component to support multiple vectorisation and annotation schemes in a future PR.

2024-07-30 15:08 UTC, reuterbal requested changes
Thanks, this looks great and removes the indeed awkward cross-referencing to utilities in the Base class, even from outside the SCC transformations.

We should consider creating dedicated tests for these utilities at some point - not mandating this for the PR but maybe create an issue to track this?

Finally, I have paid a little more attention to the new get_local_arrays utility and noticed that we might have a case-sensitivity problem there. Would be good to resolve that (or prove me wrong) before merging.

2024-08-01 09:59 UTC, mlange05 commented on loki/transformations/utilities.py
> +    arg_names = tuple(a.name for a in routine.arguments)
Yes

2024-08-01 09:59 UTC, mlange05 commented on loki/transformations/utilities.py
> +    arrays = [v for v in arrays if v.name not in arg_names]
Well spotted! I pushed a fix and tests for this now.

2024-08-01 10:01 UTC, mlange05 commented
@reuterbal You are, of course, right about the testing. I've added at least rudimentary test coverage for each utility routine. As part of that I spotted an annoying inconsistency, that I also fixed: `get_loop_bounds` would simply return strings and leave the symbol resolution to the upstream call. I've now moved this, which makes testing nicer and removes redundancy. So, please take another look.

2024-08-01 11:15 UTC, reuterbal reviewed
Thanks, the changes look fantastic and also very much agreed on the change to the return type of get_loop_bounds! Much appreciate the additional testing!

Unless CI throws up some issues this is good to go!

2024-08-01 11:15 UTC, reuterbal approved these changes

2024-08-01 12:26 UTC, merged