Transpilation: optional arguments
ecmwf-ifs/loki pull request #385
Opened 2024-09-30 14:17 UTC by MichaelSt98

Allow/handle optional arguments for c-like-backends.
For 

* `cgen` - assume all optional arguments are passed (inherently unsafe, thus warn)
* `cppgen` (and all backends derived from that) - proper handling via optional argument with default value `nullptr`
    * arguments that would have been passed by value are instead passed as pointer if they are optional

Moreover, introduced capabilities to jit compile C++ files (in addition to C files).

2024-10-04 15:52 UTC, reuterbal requested changes
Very neat! A few minor nitpicks but otherwise good to go

2024-10-05 10:16 UTC, MichaelSt98 commented on loki/transformations/transpile/fortran_c.py
> +        #     return '.cu'
More or less ... CLOUDSC and other stuff currently assumes the CUDA files to have the file suffix `.c`. However, I want to change/fix that rather soon and make it `.cu`.

2024-10-05 10:34 UTC, MichaelSt98 commented on loki/backend/cgen.py
> +            return self.format('true /*ATTENTION: present({%s})*/', expr.parameters[0].name)
Inlining allows to check whether an optional argument is present or not for a specific call. Here, we do not know whether the optional argument is present or not (at least for `cppgen` and derivatives of it). For `cgen` I decided to just assume that the optional argument is present (which is of course inherently unsafe but allows me to have at least some support for optional arguments for `cgen`). Anyway, I could do what you suggested but I would need to provide `resolve_vector_notation` with the information which backend is used in the end and/or introduce a flag with `assume_present=None/False/True`. Moreover, for `cppgen`/`cudagen`/... I skip the `DeReferenceTrafo` with the current approach.
To put it in a nutshell, yes we could do that and yes this is probably how it should be done in the end but I don't think it is worth doing it like that at the moment.
Please, let me know what you think about that.

2024-10-07 07:07 UTC, reuterbal commented on loki/backend/cgen.py
> +            return self.format('true /*ATTENTION: present({%s})*/', expr.parameters[0].name)
Ah, understood. Thanks for clarifying! If this becomes relevant for pure C transpilation, we might want to make stripping optional arguments or something like that, with the corresponding dead code elimination, a separate step of the transpilation pipeline in the future. But no need to act on it now.
As a workaround, the backend solution seems sensible.

2024-10-07 07:08 UTC, reuterbal commented on loki/transformations/transpile/fortran_c.py
> +        #     return '.cu'
Understood. It'd be fine with me to register the intention with the commented code but a comment explaining this would be helpful.

2024-10-07 07:09 UTC, reuterbal approved these changes
Many thanks, looks great! I'll do a rebase and merge once green

2024-10-07 09:11 UTC, mlange05 approved these changes
Very nice! Looks great, GTG. :shipit:

2024-10-07 11:27 UTC, merged