Continued: F2C/CUDA transpilation
ecmwf-ifs/loki pull request #424
Opened 2024-10-31 13:51 UTC by MichaelSt98

Mostly related to nested/multi-level kernel calls:

* `__device__` prefix
* kwargs to args (also for inline calls)
* call name adaptation -> `<call/function name>_c`
* ...

2024-11-07 15:12 UTC, reuterbal requested changes
Thanks, this looks good. I would like to change the naming of the new methods for InlineCall. I got bitten by the difference in behaviour and we should make this explicit.

2024-11-07 15:12 UTC, reuterbal commented on loki/expression/symbols.py
> +    def convert_kwargs_to_args(self):
Same here: `clone_with_kwargs_as_args`?

2024-11-07 15:25 UTC, MichaelSt98 commented on loki/transformations/transpile/fortran_c.py
> +                call.convert_kwargs_to_args()
That is correct!
Would it make more sense to make this an in-place update (if it is feasible and reasonable?) ?

2024-11-07 15:27 UTC, MichaelSt98 commented on loki/expression/symbols.py
> +    def check_kwarguments_order(self):
Sure! However, that means we would have a differing API compared to the `CallStatement` IR node (although the behaviour is the same not like the convert thingy).

2024-11-08 14:54 UTC, reuterbal commented on loki/expression/symbols.py
> +    def check_kwarguments_order(self):
Ah, yes, we should be consistent. Would it make sense to change it there, too?

2024-11-08 14:56 UTC, reuterbal commented on loki/transformations/transpile/fortran_c.py
> +                call.convert_kwargs_to_args()
That could be an option but I don't think we can rebuild expression nodes in-place. (Correct me if I'm wrong @mlange05)

2024-11-08 14:56 UTC, MichaelSt98 commented on loki/expression/symbols.py
> +    def check_kwarguments_order(self):
Yes, I think we can and should do that 👍

2024-11-19 15:25 UTC, reuterbal approved these changes
Many thanks for the changes! I think this looks ready now!

2024-11-19 22:39 UTC, merged