Transformation to call loop transform utilities
ecmwf-ifs/loki pull request #430
Opened 2024-11-06 13:34 UTC by awnawab

A transformation to run the loop transform utilities in a specified order, with the aim to place this transformation in scheduler pipelines.

2024-11-06 21:11 UTC, reuterbal requested changes
Thanks, conceptually this looks good but there's a few improvements that we should do right away to not require breaking the interface afterwards.

I've left inline comments, too, but to summarise:

- [ ] I would like to have explicit on-switches for each utility, with each off by default
- [ ] For the RemoveCodeTransformation, we renamed the utilities with `do_` prefix. We could use the same pattern here, e.g., call the relevant on-switch `loop_fusion` and the corresponding utility `do_loop_fusion`. This makes for a nicer config file appearance (@mlange05, any opinion on this?)
- [ ] We need a test that verifies the switches and their effectiveness by testing the full permutation matrix of all values

2024-11-06 21:11 UTC, reuterbal commented on loki/transformations/transform_loop.py
> +        loop_unroll(routine, warn_iterations_length=self.warn_iterations_length)
I would prefer having off switches for the individual loop transformations, with them disabled by default the same way we have this in the RemoveCodeTransformation:
https://github.com/ecmwf-ifs/loki/blob/c998cda4f465e34d17aeaf2e4803622ff4150522/loki/transformations/remove_code.py#L103-L110

Each of the utilities is on the more costly side of transformations, and if one of them is causing problems it's also handy to selectively switch them on or off. 

We should then also add a test that is parameterised such that each is switched on/off and that verifies that only the respective transformation is then active.

2024-11-06 21:11 UTC, reuterbal commented on loki/transformations/transform_loop.py
> +            warn_iterations_length=True
Without the loop transformation context these options are a little hard to map mentally. I suggest we prefix them according to the transformation they belong to:
```suggestion
            self, interchange_project_bounds=False,
            fission_auto_promote=True, fission_warn_loop_carries=True,
            unroll_warn_iterations_length=True
```

2024-11-08 12:45 UTC, awnawab commented
Many thanks @reuterbal for the detailed review and feedback 🙏 I've implemented all of your suggestions, please have a look again whenever you can.

2024-11-08 13:26 UTC, awnawab commented on loki/transformations/tests/test_transform_loop.py
> +def test_transform_loop_transformation(frontend, loop_trafo):
Ah yes, that is a much more comprehensive test, thanks!

2024-11-08 14:56 UTC, merged