Pipeline-plan duplicate/remove transformation changing dependencies
ecmwf-ifs/loki pull request #462
Opened 2024-12-18 15:53 UTC by MichaelSt98

Proof-of-concept transformations `DuplicateKernel` and `RemoveKernel` with both changing the dependencies for the scheduler.

This builds on top of #453 

`DuplicateKernel`  takes a kernel and creates a duplicated kernel with corresponding duplicated items and adds a call to this duplicated kernel.

`RemoveKernel` removes a kernel from the scheduler and also removes the call.

2024-12-19 08:04 UTC, MichaelSt98 commented
@mlange05 and @reuterbal I would wait for some short feedback before I add more tests to improve code coverage

2024-12-20 12:47 UTC, reuterbal requested changes
_Many_ thanks for this, this is a very useful demonstration of this functionality!

Conceptually, there's a few gotchas and things that I would prefer to do differently, and I'll try to explain here:

1. Item creation should always go through the item_factory, and the introduced `clone` method shortcuts this. Instead, we should have a `get_or_create_from_item` method or similar on the ItemFactory, to make sure any new items automatically land in the cache.

2. You inject the dependency changes incurred from plan_data in the `dependencies` property. However, that property returns (and I would like to keep it that way) IR nodes that constitute the dependency, e.g., `CallStatement`, `Import`, etc. So, we have two options: (a) inject (and remove) relevant IR nodes during planning to fake these dependencies or (b) inject the plan dependencies at a point where we are already working with items. I think (b) is a little easier and I have explored doing this via `create_dependency_items` instead, which seems to work (more details below).

3. The need for a recursive clone can be inferred from not specifying an IR to the clone method. For contained subroutines in ProgramUnit we are already doing this, and I would prefer to do the same for source files instead of introducing a new rebuild-method on scoped nodes.

4. We need to separate plan and trafo in the tests - both need to be able to apply the relevant sgraph topology changes independently, because we run either plan or trafo mode in practice. Getting both to work, i.e., trafo after plan, might be rather tricky but I also don't see a need for that at the moment.

Admittedly, half the observations above I only figured out when starting to play with this directly and trying to apply the relevant changes. So, I've decided not to bother you with too many inline comments that I kept editing and changing and I will instead file a PR on top of yours against your PR branch. I hope this doesn't come across as dismissive, but I've underestimated how fiddly this gets...

2024-12-20 12:48 UTC, reuterbal commented
Ah, I forgot to delete the inline comments. Disregard them or at least don't action on them, yet :)

2024-12-20 13:20 UTC, MichaelSt98 commented
> _Many_ thanks for this, this is a very useful demonstration of this functionality!
> 
> Conceptually, there's a few gotchas and things that I would prefer to do differently, and I'll try to explain here:
> 
> 1. Item creation should always go through the item_factory, and the introduced `clone` method shortcuts this. Instead, we should have a `get_or_create_from_item` method or similar on the ItemFactory, to make sure any new items automatically land in the cache.
> 2. You inject the dependency changes incurred from plan_data in the `dependencies` property. However, that property returns (and I would like to keep it that way) IR nodes that constitute the dependency, e.g., `CallStatement`, `Import`, etc. So, we have two options: (a) inject (and remove) relevant IR nodes during planning to fake these dependencies or (b) inject the plan dependencies at a point where we are already working with items. I think (b) is a little easier and I have explored doing this via `create_dependency_items` instead, which seems to work (more details below).
> 3. The need for a recursive clone can be inferred from not specifying an IR to the clone method. For contained subroutines in ProgramUnit we are already doing this, and I would prefer to do the same for source files instead of introducing a new rebuild-method on scoped nodes.
> 4. We need to separate plan and trafo in the tests - both need to be able to apply the relevant sgraph topology changes independently, because we run either plan or trafo mode in practice. Getting both to work, i.e., trafo after plan, might be rather tricky but I also don't see a need for that at the moment.
> 
> Admittedly, half the observations above I only figured out when starting to play with this directly and trying to apply the relevant changes. So, I've decided not to bother you with too many inline comments that I kept editing and changing and I will instead file a PR on top of yours against your PR branch. I hope this doesn't come across as dismissive, but I've underestimated how fiddly this gets...

That is perfectly fine for me and I wasn't expecting this PR to go in as it is but to serve as a first step/proof of concept.

2025-01-10 09:42 UTC, MichaelSt98 commented
Multi-level call tree duplication/removal for a follow-up PR.

2025-01-10 12:35 UTC, reuterbal approved these changes
Thanks for mopping up the outstanding housekeeping tasks, @MichaelSt98!

I think this is ready for integration, more testing and expansion to multi-level graph changes etc. should happen in follow-up PRs.

2025-01-10 12:49 UTC, mlange05 approved these changes
Agreed! Looks great now and next steps go into follow-ons. Many thanks to both! GTG :shipit:

2025-01-10 12:50 UTC, merged