Naml remove custom entry points
ecmwf-ifs/loki pull request #465
Opened 2024-12-24 05:09 UTC by mlange05

_Note: This sits on top of PR #464 and requires CLOUDSC  CLOUDSC PR 106 to be merged first._

_Note: For testing only at this stage._

Following the conversion to config-file based pipelines, this PR now removes all the custom entry point options under `loki-transform.py convert` and their associated use in CMake macros. It also removes the now unused `loki_transform_convert` entry point.

2025-01-16 19:47 UTC, reuterbal requested changes
This is _very_ pleasing to see!

In addition to removing the processing of the CMake options we should directly remove them from the corresponding function interfaces - this will make sure to hard fail with an error instead of silently ignoring deprecated options, which I think is better at this stage.

2025-01-16 19:47 UTC, reuterbal commented on cmake/loki_transform.cmake
> -        if( _PAR_T_INLINE_MEMBERS )
With these removed, we should now also remove the corresponding arguments from the CMake function - that will make sure that any options that have been specified are not silently ignored but do actually raise an error in CMake directly. For that, ll. 226-231 need to look like this:

```cmake
    set( options NO_PLAN_SOURCEDIR COPY_UNMODIFIED CPP CPP_PLAN )
    set( single_value_args TARGET COMMAND MODE FRONTEND CONFIG PLAN )
    set( multi_value_args SOURCES HEADERS DEFINITIONS INCLUDES )
```

Please also update the docstring to match the reduced interface.

2025-01-16 19:47 UTC, reuterbal commented on cmake/loki_transform_helpers.cmake
> -    if( _PAR_DATA_OFFLOAD )
With these removed, the argument definition to `loki_transform` (ll. 48-57 in `loki_transform.cmake`) should be updated accordingly:
```cmake
    set( options CPP )
    set( oneValueArgs COMMAND MODE FRONTEND CONFIG BUILDDIR )
    set( multiValueArgs OUTPUT DEPENDS SOURCES HEADERS INCLUDES DEFINITIONS OMNI_INCLUDE XMOD )
```
Please also update the docstring of `loki_transform` accordingly.

Also, since we only have the `CPP` option left now, it might be worthwhile to just remove this macro and instead inline the remaining 3 lines of code into `loki_transform` and `loki_transform_plan` directly

2025-01-16 19:47 UTC, reuterbal commented on scripts/loki_transform.py
> +        msg = '[Loki] ERROR: Pipeline or transformation mode not found in config file.\n'
Might be helpful to mention the specified mode here, to spot typos quickly:
```suggestion
        msg = f'[Loki] ERROR: Pipeline or transformation mode "{mode}" not found in config file.\n'
```

2025-01-16 19:47 UTC, reuterbal commented on scripts/loki_transform.py
> +    if not mode in config.pipelines:
Pet peeve, I find this much more readable:
```suggestion
    if mode not in config.pipelines:
```

2025-01-17 07:30 UTC, mlange05 commented
@reuterbal Indeed, very satisfying! 😉  Thanks for the pointers, I think it's ready for another look.

2025-01-17 09:52 UTC, reuterbal approved these changes
Many thanks!

2025-01-17 09:53 UTC, merged